# not-burxt: gap — checks THIS REPOSITORY rather than the format, so the standalone argument never reached it
"""The landing page's showcase: one document becoming a whole page, with a slider over its two halves.

    burxt build render.bx -o bmxrender
    python3 showcase.py        # -> ../docs/_includes/showcase.html

**Live HTML rather than a screenshot**, and that is the whole reason it exists: a picture cannot be
checked and a rendered page can. Everything inside the browser frame is real `bmxrender` output from
`shop.bmx`, injected at generation time. Hand-written HTML pretending to be renderer output is the same
defect as a spec sentence nobody ran.

**One document, and no HTML anywhere — which took Andre asking twice to get right.**

The first two versions showed a `.bmx` beside a `layout.html`, on the theory that BMX cannot express a
navigation bar and a host template has to supply it. Then he asked *"you really need html?"*, and the
measurement said no:

    # Roast&Co            ->   <h1>Roast&amp;Co</h1>
    - [Coffee](/coffee)   ->   <ul><li><a href="/coffee">Coffee</a></li> ...

A bar is a brand and a row of links, and BMX renders both today. What BMX has no syntax for is
*attributes* — so the stylesheet selects structurally (`.bmx > h1` is the brand, `.bmx > p:first-of-type`
is the link row) instead of by class. That is the real boundary, and it is far narrower than the one I
had asserted in two captions. The honest caveat, which the page states rather than hides: a positional
selector is brittle, and `:nav:` is the fix — a block names the region, and a host that declares `nav`
renders it however it likes. `bmxrender` refuses blocks by design (`BMX-R003`), which is why this page
does not use one, and it is exactly the hook a framework builds on.

So the slider is over halves of ONE document rather than over two files: **the bar**, **the content**,
and the whole page. The result blurs — Andre's idea, and better than a caption, because the whole page
stays on screen and a reader sees *where* the split falls instead of reading about it.

**Four rules this file follows, each because the alternative has already gone wrong here:**

*The source panel is the file that was rendered*, read at generation time. A panel retyped by hand can
disagree with the output above it and the picture would still look right.

*The line count in the prose is counted, not typed.* An earlier version said "nine lines" of a file that
is eleven, with all eleven of them visible directly beneath the sentence.

*The slider is CSS only.* Radio inputs and sibling selectors, no JavaScript — the site's `.picker`
styling exists but its behaviour lived in a page-local script on another site, and a showcase that needs
a script is a showcase that is blank when the script does not load.

*The panel is marked `language-bmx` so `code.js` colours it*, rather than this file shipping a second
colouriser. `code.js` selects `pre > code.language-bmx`; emitting that markup is the whole integration.
"""

import html
import subprocess

body = subprocess.run(["./bmxrender", "shop.bmx"], capture_output=True, text=True).stdout.strip()
doc_src = open("shop.bmx").read().rstrip()
source = html.escape(doc_src)

# Counted here rather than typed into the prose below, because the panel showing every line sits
# directly beneath the sentence claiming how many there are. A digit rather than a word: the first
# version was a word table that stopped at fourteen and raised on a fifteen-line file, and a table with
# a ceiling is a defect waiting for the document to grow. The sentence is worded so it never leads.
doc_lines = str(len(doc_src.splitlines()))

SHOWCASE = """<!-- GENERATED by tools/showcase.py from tools/shop.bmx. Do not edit: regenerate. -->
<div class="showcase">
  <input type="radio" name="showcase" id="sc-bar">
  <input type="radio" name="showcase" id="sc-body">
  <input type="radio" name="showcase" id="sc-all" checked>

  <fieldset class="picker">
    <legend>What this shows</legend>
    <label for="sc-bar">The bar</label>
    <label for="sc-body">The content</label>
    <label for="sc-all">The whole page</label>
  </fieldset>

  <div class="win">
    <div class="chrome">
      <span class="dot r"></span><span class="dot y"></span><span class="dot g"></span>
      <span class="url">roastandco.example/shop</span>
    </div>
__BODY__
  </div>

  <figure class="src">
    <figcaption>shop.bmx <span>the whole page, and the only file</span></figcaption>
    <pre><code class="language-bmx">__SOURCE__</code></pre>
  </figure>

  <p class="showcase-note bar-note">The bar is <strong>the heading and the row of links</strong> — the
  first two lines of the document. BMX has no attribute syntax, so the stylesheet reaches them by
  position rather than by class: <code>.bmx &gt; h1</code> is the brand, the first <code>p</code> is the
  links. Brittle on purpose, to show where the seam is — <code>:nav:</code> is how you name the region
  instead, and your framework decides what it renders as.</p>
  <p class="showcase-note body-note">The content is markdown doing what markdown does: a heading, a
  paragraph, a list, a quote, a link. The cards are list items and the thumbnails are CSS gradients —
  BMX has no image syntax (<code>SPEC.md</code> §7).</p>
  <p class="showcase-note all-note">One document, __DOC_LINES__ lines, and <strong>no HTML
  anywhere</strong> — the bar, the search box, the buttons, the cards, the quote, the price. A document
  and a stylesheet, which is what every page has.</p>
</div>
"""

# Placeholders rather than `%`-formatting or f-strings: the fragment carries braces and `&gt;`, and both
# of those forms read one of them — the same lesson the retired `hero.py` learned from `border-radius:50%`.
open("../docs/_includes/showcase.html", "w").write(
    SHOWCASE.replace("__BODY__", body)
            .replace("__SOURCE__", source)
            .replace("__DOC_LINES__", doc_lines)
)
print("wrote docs/_includes/showcase.html")
